name: Build Jekyll and Deploy to Another Repo via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'       # 建议与您本地版本一致
          bundler-cache: true        # 这会自动读取 Gemfile.lock 并安装精确版本的 gem

      - name: Build with Jekyll
        run: bundle exec jekyll build  # 必须使用 bundle exec

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2 # 使用支持SSH的Action
        env:
          # 关键步骤：使用你存在Secrets里的SSH私钥
          SSH_DEPLOY_KEY: ${{ secrets.JEKYLL_DEPLOY_KEY }}
        with:
          source-directory: '_site' # 要推送的文件夹
          destination-git-username: 'actionsbot' # 可以是任意名字，用于git commit
          destination-git-email: 'bot@github.com'
          destination-repository-name: 'lm-xiao-fen/jekyll-html' # 目标仓库
          target-branch: 'main' # 目标分支
          # 无需再配置任何token!
